[workspace]
members = ["stylus-sdk", "stylus-proc"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Offchain Labs"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/OffchainLabs/stylus-sdk-rs"
repository = "https://github.com/OffchainLabs/stylus-sdk-rs"

[workspace.dependencies]
alloy-primitives = "0.3.1"
alloy-sol-types = "0.3.1"
derivative = "2.2.0"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
keccak-const = "0.2.0"
lazy_static = "1.4.0"
sha3 = "0.10.8"

# data structures
fnv = "1.0.7"

# proc macros
syn = { version = "1.0", features = ["full"] }
paste = "1.0.14"
quote = "1.0"
regex = "1.9.1"
proc-macro2 = "1.0"
syn-solidity = "=0.3.1"
convert_case = "0.6.0"

# members
stylus-sdk = { path = "stylus-sdk" }
stylus-proc = { path = "stylus-proc" }
