[package]
name = "stylus-sdk"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
alloy-primitives = { git = "https://github.com/rachel-bousfield/alloy-core.git", branch = "native-keccak" }

[workspace]
