[package]
name = "stylus-sdk"
keywords = ["arbitrum", "ethereum"]

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
derivative.workspace = true
fnv.workspace = true
hex = { workspace = true, default-features = false, features = ["alloc"] }
alloy-primitives.workspace = true
lazy_static.workspace = true

# local deps
stylus-proc.workspace = true
